# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_bisection_pvals_cpp <- function(beta_post, n_iter, interval_type) {
    .Call(`_bclogit_calc_bisection_pvals_cpp`, beta_post, n_iter, interval_type)
}

process_matched_pairs_cpp <- function(strata, y, X, treatment) {
    .Call(`_bclogit_process_matched_pairs_cpp`, strata, y, X, treatment)
}

